version: "3.9"
name: bun-svelte

networks:
  bun_network:
    driver: bridge

services:
  bun-svelte-app:
    container_name: bun-svelte-app
    # The name of the image that will be created when building this container
    image: bun-svelte-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - bun_network
    ports:
      - 3010:3000